### ISSUE TITLE
Modify Seer's Stone so that there is "charged" and "uncharged" versions

### ISSUE THREAD

**Issue by ax-vasquez** [ax-vasquez/enchantments-seer#31]
# Description

This issue will address two issues:
1. It seems like it will suck serious butt to implement custom crafting logic to "intercept" the vanilla crafting event
    * _There may be a way to subscribe to this event and simply check if the item being crafted is the Seer's Stone - we can investigate this later if we want to switch back_
2. It would enable people to automate the creation of Seer's Stone (u) and selective use of charging stones later

## To do
1. [x] Register new "Seer's Stone (u)" item - this is the "uncharged" Seer's Stone
   * [x] Update the Seer's Stone recipe file to point to the "Seer's Stone (u)" item
       * The idea is that the "uncharged" stone should be the only craftable one
2. [x] Keep the "old" Seer's Stone _registration_ as-is
    * There shouldn't be any recipe file for this item; it will be created by charging the stone on the Seer's Enchanting Table
3. [x] Enable players to craft a Charged Seer's Stone with nine Uncharged Seer's Stones.

**Comment by armstrongl** [comment]
## Some context 

We decided to alter the Seer's Stone so that it has two possible states: 
- **Charged**
- **Uncharged** 

You can only use Charged Seer's Stones to enchant.

When you craft a Seer's Stone, it starts out as Uncharged. You can charge a Seer's Stone by placing it on the Seer's Enchanting Table and consuming 10 XP (configurable; see Configuration options below). 

### Visible differences
The only difference between the two states is that the Charged Seer's Stone is _foiled_ and the Uncharged Seer's Stone is _not foiled_.

### Configuration options
We plan on making this feature configurable through the mod configuration file in the following ways:
- You can adjust the XP cost of charging the Seer's Stone.
    - Default: `10`
    - Valid range: `0-100`
- You can alter the mod so that the Seer's Enchanting Table consumes hearts instead of XP. 
    - Default: `xp`
    - Valid options: `xp`, `hearts`
- If you opt to use hearts to charge Seer's Stone, the number of hearts consumed is also configurable. 
    - Default: `5`
    - Valid range: `0-50`
- You change the default state of the Seer's Stones upon creation.
    - Default: `uncharged`
    - Valid options: `uncharged`, `charged`
> See https://github.com/ax-vasquez/enchantments-seer/issues/34

**Comment by armstrongl** [comment]
We've encountered what we believe is a Forge-related issue where we can successfully craft the Uncharged Seer's Stone and the Charged Seer's Stone, but the recipes aren't listed in JEI. We're leaving it as-is for now but we'll revisit it later. 

For now, you can craft the Uncharged Seer's Stone as you could originally craft the Seer's Stone and you can craft the Charged Seer's Stone with nine Uncharged Seer's Stones (no XP cost). We figured this was a fair way to allow players to create Charged Seer's Stones without using XP. 

Uncharged Seer's Stone recipe:
![image](https://user-images.githubusercontent.com/29762984/132262316-84a8816b-1814-4efa-91e0-ed7a630133d3.png)

Charged Seer's Stone recipe:
![image](https://user-images.githubusercontent.com/29762984/132262311-9912cc67-571c-4f16-bab9-f287642441bc.png)

In a later PR, we'll enable users to charge Seer's Stones at the Seer's Enchanting Table.

**Comment by ax-vasquez** [comment]
Minor nitpick - let's change the display name for the charged Seer's Stone to "Seer's Stone" and the uncharged Seer's Stone to "Seer's Stone (u)"

I'm being a total nerd here - this is the syntax used by RuneScape :D

**Comment by armstrongl** [comment]
See #33
